# Generated by Django 3.0.3 on 2020-05-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qty',
        ),
    ]
