# Generated by Django 3.0.3 on 2020-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_delete_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
    ]
