# Generated by Django 3.0.3 on 2020-04-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, verbose_name='Category')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('discountprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Price')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('prodIsNew', models.BooleanField(default=True, verbose_name='Is New')),
                ('prodBestSeller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category', verbose_name='Category')),
            ],
        ),
        migrations.DeleteModel(
            name='produit',
        ),
    ]
