# Generated by Django 3.0.3 on 2020-05-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200429_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=100, verbose_name='Forme')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=100, verbose_name='Sexe')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='forme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Forme', verbose_name='Forme'),
        ),
        migrations.AddField(
            model_name='product',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marque', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='product',
            name='sexe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Sexe', verbose_name='Sexe'),
        ),
    ]
