# Generated by Django 3.0.3 on 2020-05-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200501_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexe',
            name='desc',
        ),
    ]
