# Generated by Django 3.0.3 on 2020-05-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200510_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite',
        ),
    ]
