# Generated by Django 3.0.3 on 2020-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20200521_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(choices=[('red', 'red'), ('black', 'black')], max_length=100, verbose_name='Color '),
        ),
    ]
