# Generated by Django 3.0.3 on 2020-05-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200521_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color1',
            new_name='color',
        ),
    ]
