# Generated by Django 3.0.3 on 2020-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200521_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colorr',
        ),
    ]
