# Generated by Django 3.0.3 on 2020-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20200521_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colorr',
            field=models.CharField(choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200')], max_length=100, verbose_name='Color '),
        ),
    ]
