# Generated by Django 3.0.3 on 2020-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20200521_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color3',
        ),
        migrations.AddField(
            model_name='product',
            name='colorrr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200')], max_length=100, null=True, verbose_name='Color 2 '),
        ),
        migrations.AddField(
            model_name='product',
            name='colorrrr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200')], max_length=100, null=True, verbose_name='Color 3 '),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorr',
            field=models.CharField(choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200')], max_length=100, verbose_name='Color 1 '),
        ),
    ]
