# Generated by Django 3.0.3 on 2020-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20200521_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colorrr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colorrrr',
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=models.BooleanField(default=False, verbose_name='Color 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='color3',
            field=models.BooleanField(default=False, verbose_name='Color 3'),
        ),
    ]
