# Generated by Django 3.0.3 on 2020-05-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20200521_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200'), ('#ff9ff3', '#ff9ff3')], max_length=100, null=True, verbose_name='color '),
        ),
        migrations.AddField(
            model_name='product',
            name='colorrr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200'), ('#ff9ff3', '#ff9ff3')], max_length=100, null=True, verbose_name='colorrr '),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('#E69200', '#E69200'), ('#ff9ff3', '#ff9ff3')], max_length=100, null=True, verbose_name='colorr '),
        ),
    ]
