# Generated by Django 3.0.3 on 2020-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20200522_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colorr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('goldenrod', 'goldenrod'), ('pink', 'pink')], max_length=100, null=True, verbose_name='colorr '),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorrr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('goldenrod', 'goldenrod'), ('pink', 'pink')], max_length=100, null=True, verbose_name='colorr '),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorrrr',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('black', 'black'), ('goldenrod', 'goldenrod'), ('pink', 'pink')], max_length=100, null=True, verbose_name='colorrr '),
        ),
    ]
