# Generated by Django 3.0.3 on 2020-05-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20200522_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matière',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matière', models.CharField(max_length=100, verbose_name='Matière')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='matière',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Matière', verbose_name='Matière'),
        ),
    ]
