# Generated by Django 3.0.3 on 2020-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, choices=[('Achat en ligne', 'Achat en ligne'), ('Information sur nos produits', 'Information sur nos produits')], max_length=50, null=True),
        ),
    ]
