# Generated by Django 3.0.3 on 2020-05-17 21:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200517_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
