# Generated by Django 3.0.3 on 2020-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, default=20202020, null=True),
        ),
    ]
