# Generated by Django 3.0.3 on 2020-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200517_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='countryphone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
